matrix:
  include:
    - language: cpp
      before_install:
        - pip install --user cpp-coveralls
      script: bash /bin/utils/cpp/test.sh

    - language: cpp
      before_install:
        - pip install --user cpp-coveralls
      script: bash /bin/poseidon/beaglebone/system/test.sh

    - language: cpp
      before_install:
        - pip install --user cpp-coveralls
      script: bash /bin/poseidon/raspberryPI/test.sh

    - language: node_js
      node_js:
        - "node"
      script: bash /bin/utils/javascript/test.sh
