matrix:
  include:
    - language: cpp
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - socat
      before_install:
        - pip install --user pyyaml cpp-coveralls
        - chmod +x bin/runUnitTests_Cpp.sh
      script: ./bin/runUnitTests_Cpp.sh

    - language: node_js
      node_js:
        - "node"
        - "4"
      before_install:
        - chmod +x bin/runUnitTests_Javascript.sh
      script: ./bin/runUnitTests_Javascript.sh
