matrix:
  include:
    - language: cpp
      env:
        - title=utils/cpp
      before_install:
        - pip install --user cpp-coveralls
      install:
        - sudo apt-get install -y libopencv-dev
      script: bash bin/utils_cpp_test.sh

    - language: node_js
      env:
        - title=utils/javascript
      node_js:
        - "node"
      script: bash bin/utils_javascript_test.sh

    - language: cpp
      env:
        - title=utils/arduino
      before_install:
        - pip install --user cpp-coveralls platformio
      script: bash bin/utils_arduino_test.sh
