#ifndef PIN_MAP
#define PIN_MAP

#define KILL_PIN 3
#define ECHO_RETURN 42

// motor pins
#define FRONT_MOTOR_PIN 3
#define BACK_MOTOR_PIN 4
#define LEFT_MOTOR_PIN 5
#define RIGHT_MOTOR_PIN 6

// motor trims
#define MOTOR_REVERSE_MAX -0.9
#define MOTOR_REVERSE_MIN -0.1
#define MOTOR_CENTER 0
#define MOTOR_FORWARD_MIN 0.1
#define MOTOR_FORWARD_MAX 0.9
#define MOTOR_DEFAULT_TRIM {MOTOR_REVERSE_MAX, MOTOR_REVERSE_MIN, MOTOR_CENTER, MOTOR_FORWARD_MIN, MOTOR_FORWARD_MAX}

#define LOOP_DELAY 1

#endif
