#ifndef PIN_MAP
#define PIN_MAP

#define LEFT_MOTOR_SPEED 5
#define LEFT_MOTOR_FORWARD 7
#define LEFT_MOTOR_BACKWARD 8

#define RIGHT_MOTOR_SPEED 6
#define RIGHT_MOTOR_FORWARD 13
#define RIGHT_MOTOR_BACKWARD 12

#define KILL_PIN 3
#define TEST_MOTOR_PIN 4
#define ECHO_RETURN 42

#endif
